# Pytorch cookbook
A list of recipes that I find useful when using pytorch.

In [6]:
import torch
import torch.nn.functional as F

### Broadcasting

In [7]:
# Tensor A with shape (3, 1)
A = torch.tensor([[1],
                  [2],
                  [3]])

# Tensor B with shape (1, 4)
B = torch.tensor([[10, 20, 30, 40]])

# Broadcasting allows element-wise addition
C = A + B
print("Result of A + B:\n", C)

Result of A + B:
 tensor([[11, 21, 31, 41],
        [12, 22, 32, 42],
        [13, 23, 33, 43]])


### Reduce & transformations on dimensions - 0 or 1

In [5]:
# Create a tensor with shape (2, 4) with hard-coded numbers
tensor = torch.tensor([[0.0, 2.0, 3.0, 5.0],
                       [0.0, 2.0, 3.0, 5.0]])

# Normalize the tensor along dimension 0
# Reduces (dim0 = rows) so output tensor will be [1, n]
# Output rows = 1, columns = n
sum_dim0 = tensor.sum(dim=0, keepdim=True)

# Normalize the tensor along dimension 1
# Reduces (dim1 = columns) so output tensor will be [m, 1]
# Output rows = m, columns = 1
sum_dim1 = tensor.sum(dim=1, keepdim=True)
print("Original Tensor:\n", tensor, "\nShape:", tensor.shape, "\n")
print("Sum along dim=0:\n", sum_dim0, "\nShape:", sum_dim0.shape, "\n")
print("Sum along dim=1:\n", sum_dim1, "\nShape:", sum_dim1.shape, "\n")




Original Tensor:
 tensor([[0., 2., 3., 5.],
        [0., 2., 3., 5.]]) 
Shape: torch.Size([2, 4]) 

Sum along dim=0:
 tensor([[ 0.,  4.,  6., 10.]]) 
Shape: torch.Size([1, 4]) 

Sum along dim=1:
 tensor([[10.],
        [10.]]) 
Shape: torch.Size([2, 1]) 

